"""Survey selection and selection-function modeling."""

from .selection import (
    split_by_survey,
    build_survey_selection_functions,
    SelectionFunctionValidator,
    generate_sf_variant,
)
from .comparison import (
    ChimeMockComparison,
    SelectionMapComparison,
    apply_common_chime_support,
    build_chime_instrumental_selection_set,
    build_chime_only_selection_set,
    build_masked_chime_instrumental_sf,
    compare_chime_selection_maps,
    extract_chime_empirical_sf,
    jensen_shannon_divergence,
    kl_divergence,
    normalize_selection_map,
    plot_chime_selection_comparison,
    plot_ratio_histogram,
    plot_empirical_vs_instrumental_scatter,
    run_chime_mock_comparison,
    selection_effective_pixels,
    selection_entropy_bits,
    summarize_wtheta_difference,
    plot_wtheta_comparison,
)

__all__ = [
    "split_by_survey",
    "build_survey_selection_functions",
    "SelectionFunctionValidator",
    "generate_sf_variant",
    "ChimeMockComparison",
    "SelectionMapComparison",
    "apply_common_chime_support",
    "build_chime_instrumental_selection_set",
    "build_chime_only_selection_set",
    "build_masked_chime_instrumental_sf",
    "compare_chime_selection_maps",
    "extract_chime_empirical_sf",
    "jensen_shannon_divergence",
    "kl_divergence",
    "normalize_selection_map",
    "plot_chime_selection_comparison",
    "plot_ratio_histogram",
    "plot_empirical_vs_instrumental_scatter",
    "run_chime_mock_comparison",
    "selection_effective_pixels",
    "selection_entropy_bits",
    "summarize_wtheta_difference",
    "plot_wtheta_comparison",
]
